/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Invoice, Project, Consultant, Task, KnowledgeDoc } from './types';

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'INV-2023-089',
    client: 'Stellar Corp',
    project: 'Cloud Migration Phase 2',
    amount: 42500,
    dueDate: 'Oct 12, 2023',
    status: 'Paid',
  },
  {
    id: 'INV-2023-094',
    client: 'Nexis Systems',
    project: 'AI Implementation',
    amount: 18200,
    dueDate: 'Oct 28, 2023',
    status: 'Pending',
  },
  {
    id: 'INV-2023-078',
    client: 'Global Logics',
    project: 'Cybersecurity Audit',
    amount: 12000,
    dueDate: 'Sep 30, 2023',
    status: 'Overdue',
  },
  {
    id: 'INV-2023-095',
    client: 'Vertex Ltd',
    project: 'Mobile App Dev',
    amount: 24900,
    dueDate: 'Nov 05, 2023',
    status: 'Pending',
  },
  {
    id: 'INV-2023-102',
    client: 'Quantum Labs',
    project: 'Data Governance Audit',
    amount: 31200,
    dueDate: 'Dec 15, 2023',
    status: 'Paid',
  }
];

export const INITIAL_PROJECT_DETAILS_MAP: Record<string, { milestones: any[], documents: any[] }> = {
  'PROJ-001': {
    milestones: [
      { id: 'm1', date: 'JAN 15', title: 'Staging Environment Config', description: 'Complete parity sync with on-prem staging for final UAT.', status: 'Completed' },
      { id: 'm2', date: 'FEB 02', title: 'Data Migration (Batch A)', description: 'Initial production database mirror to AWS RDS instance.', status: 'In Progress' },
      { id: 'm3', date: 'MAR 15', title: 'Final Production Cutover', description: 'DNS switch and legacy server decommissioning.', status: 'Planned' },
    ],
    documents: [
      { id: 'd1', title: 'Project SOW v2.4', type: 'SOW / PDF', modifiedAt: '2 days ago', size: '1.2 MB' },
      { id: 'd2', title: 'AWS Architecture Diagram', type: 'Architecture', modifiedAt: 'Yesterday', size: '4.8 MB' },
      { id: 'd3', title: 'Compliance Checklist', type: 'Audit Document', modifiedAt: '4 hours ago', size: '850 KB' },
      { id: 'd4', title: 'Invoice #KTS-00982', type: 'Billing Statement', modifiedAt: 'Jan 01, 2024', size: '120 KB' },
    ]
  }
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'PROJ-001',
    name: 'Legacy to AWS Pivot',
    description: 'Transitioning heritage ERP systems to a hybrid multi-cloud environment for EMEA operations. Includes edge computing deployment.',
    status: 'On Track',
    category: 'Cloud & Infrastructure',
    overallProgress: 68,
    startDate: 'Oct 12, 2023',
    endDate: 'Mar 15, 2024',
    spentToDate: 142500,
    leadConsultantName: 'Sarah Jenkins',
    leadConsultantRole: 'Cloud Solutions Architect',
    leadConsultantImg: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=260&auto=format&fit=crop',
    illustrationType: 'globe',
    milestones: INITIAL_PROJECT_DETAILS_MAP['PROJ-001'].milestones,
    documents: INITIAL_PROJECT_DETAILS_MAP['PROJ-001'].documents,
  },
  {
    id: 'PROJ-002',
    name: 'AI/ML Model Training',
    description: 'Developing proprietary LLM for legal document synthesis, cross-reference auditing, and continuous compliance analysis.',
    status: 'At Risk',
    category: 'AI/ML Initiatives',
    overallProgress: 32,
    startDate: 'Dec 01, 2023',
    endDate: 'Nov 30, 2024',
    spentToDate: 84000,
    leadConsultantName: 'Elena Rodriquez',
    leadConsultantRole: 'Principal Data Scientist',
    leadConsultantImg: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=260&auto=format&fit=crop',
    illustrationType: 'ai',
  },
  {
    id: 'PROJ-003',
    name: 'Q3 Cybersecurity Audit',
    description: 'Penetration testing, legacy code scanning, and structural security hardening for modern financial banking and gateway APIs.',
    status: 'Active',
    category: 'Cybersecurity',
    overallProgress: 92,
    startDate: 'Jul 15, 2023',
    endDate: 'Sep 15, 2024',
    spentToDate: 56000,
    leadConsultantName: 'David Smith',
    leadConsultantRole: 'Security Engineer',
    leadConsultantImg: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=260&auto=format&fit=crop',
    illustrationType: 'shield',
  },
  {
    id: 'PROJ-004',
    name: 'Omni-Data Lakehouse',
    description: 'A unified storage architecture optimized for highly structured query access and unstructured analytical research streams.',
    status: 'On Track',
    category: 'Data Analytics',
    overallProgress: 45,
    startDate: 'Jan 10, 2024',
    endDate: 'Mar 10, 2025',
    spentToDate: 120000,
    leadConsultantName: 'Marcus Chen',
    leadConsultantRole: 'Lead Full Stack Developer',
    leadConsultantImg: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=260&auto=format&fit=crop',
    illustrationType: 'database',
  },
  {
    id: 'PROJ-005',
    name: 'Smart City IoT Grid',
    description: 'Distributed mesh sensor network integration designed for real-time edge traffic calculations and automatic utility load monitoring.',
    status: 'Planned',
    category: 'Cloud & Infrastructure',
    overallProgress: 10,
    startDate: 'May 01, 2024',
    endDate: 'May 20, 2025',
    spentToDate: 34000,
    leadConsultantName: 'Sophia Lee',
    leadConsultantRole: 'React Native Developer',
    leadConsultantImg: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=260&auto=format&fit=crop',
    illustrationType: 'iot',
  }
];

export const INITIAL_CONSULTANTS: Consultant[] = [
  {
    id: 'CONS-001',
    name: 'Sarah Jenkins',
    role: 'Senior DevOps Architect',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=260&auto=format&fit=crop',
    rating: 4.9,
    reviews: 124,
    skills: ['AWS Lambda', 'Kubernetes', 'Terraform'],
    status: 'Available',
  },
  {
    id: 'CONS-002',
    name: 'Marcus Chen',
    role: 'Lead Full Stack Developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=260&auto=format&fit=crop',
    rating: 5.0,
    reviews: 89,
    skills: ['React', 'Node.js', 'TypeScript', 'GraphQL'],
    status: 'On Project',
  },
  {
    id: 'CONS-003',
    name: 'Elena Rodriquez',
    role: 'Principal Data Scientist',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=260&auto=format&fit=crop',
    rating: 4.8,
    reviews: 210,
    skills: ['Python', 'PyTorch', 'SQL'],
    status: 'Available',
  },
  {
    id: 'CONS-004',
    name: 'David Smith',
    role: 'Security Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=260&auto=format&fit=crop',
    rating: 4.7,
    reviews: 42,
    skills: ['Ethical Hacking', 'NIST', 'Go'],
    status: 'Out of Office',
  },
  {
    id: 'CONS-005',
    name: 'Sophia Lee',
    role: 'React Native Developer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=260&auto=format&fit=crop',
    rating: 4.9,
    reviews: 67,
    skills: ['JavaScript', 'iOS', 'Android'],
    status: 'Available',
  },
  {
    id: 'CONS-006',
    name: 'John Doe',
    role: 'Cloud Solutions Architect',
    avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=260&auto=format&fit=crop',
    rating: 4.6,
    reviews: 15,
    skills: ['Azure', 'DotNet', 'Jenkins'],
    status: 'Available',
  }
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'TASK-001',
    title: 'Fix race condition in Auth Provider',
    project: 'Legacy to AWS Pivot',
    assigneeName: 'Marcus Chen',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=260&auto=format&fit=crop',
    priority: 'Blocker',
    status: 'To Do',
    sprint: 'SP-24',
    categoryName: 'Kinetic Core Engine',
  },
  {
    id: 'TASK-002',
    title: 'Implement WebGL Dashboard Visuals',
    project: 'Omni-Data Lakehouse',
    assigneeName: 'Sarah Jenkins',
    assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=260&auto=format&fit=crop',
    priority: 'High',
    status: 'In Progress',
    sprint: 'SP-24',
    categoryName: 'Visual Analytics UI',
  },
  {
    id: 'TASK-003',
    title: 'Update API Documentation',
    project: 'Q3 Cybersecurity Audit',
    assigneeName: 'Elena Rodriquez',
    assigneeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=260&auto=format&fit=crop',
    priority: 'Low',
    status: 'Review',
    sprint: 'SP-25',
    categoryName: 'Public Gateway',
  },
  {
    id: 'TASK-004',
    title: 'Database migration failing on Staging Server',
    project: 'Legacy to AWS Pivot',
    assigneeName: 'Sarah Jenkins',
    assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=260&auto=format&fit=crop',
    priority: 'Blocker',
    status: 'In Progress',
    sprint: 'SP-24',
    categoryName: 'DevOps Platform',
  },
  {
    id: 'TASK-005',
    title: 'Implement Stripe Connect Flow',
    project: 'Smart City IoT Grid',
    assigneeName: 'John Doe',
    assigneeAvatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=260&auto=format&fit=crop',
    priority: 'High',
    status: 'In Progress',
    sprint: 'SP-24',
    categoryName: 'Payments Service',
  },
  {
    id: 'TASK-006',
    title: 'New user onboarding interactive tour flow',
    project: 'AI/ML Model Training',
    assigneeName: 'Sophia Lee',
    assigneeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=260&auto=format&fit=crop',
    priority: 'High',
    status: 'Review',
    sprint: 'SP-24',
    categoryName: 'Client Experience Portal',
  },
  {
    id: 'TASK-007',
    title: 'Refactor logging middleware structure',
    project: 'Legacy to AWS Pivot',
    assigneeName: 'Marcus Chen',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=260&auto=format&fit=crop',
    priority: 'Low',
    status: 'To Do',
    sprint: 'SP-25',
    categoryName: 'Telemetry Suite',
  }
];

export const INITIAL_KNOWLEDGE_DOCS: KnowledgeDoc[] = [
  {
    id: 'DOC-001',
    title: 'React Deployment Guide',
    category: 'DevOps',
    summary: 'Optimizing production builds for Azure Static Web Apps and CI/CD pipeline automation.',
    views: 1200,
    readTime: '5 min read',
    updatedAt: '2h ago',
    authorName: 'Sarah Jenkins',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=260&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?q=80&w=480&auto=format&fit=crop',
  },
  {
    id: 'DOC-002',
    title: 'Security Best Practices',
    category: 'Security',
    summary: 'Standard protocols for OAuth2 implementation, data encryption at rest, and PEN test requirements.',
    views: 940,
    readTime: '12 min read',
    updatedAt: '1d ago',
    authorName: 'David Smith',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=260&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=480&auto=format&fit=crop',
  },
  {
    id: 'DOC-003',
    title: 'Consultancy Playbook v4',
    category: 'Strategy',
    summary: 'Client onboarding strategies, project scope definition, and stakeholder management frameworks.',
    views: 820,
    readTime: '20 min read',
    updatedAt: '2d ago',
    authorName: 'Marcus Vane',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=260&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1531538606174-0f90ff5dce83?q=80&w=480&auto=format&fit=crop',
  },
  {
    id: 'DOC-004',
    title: 'Component Library Usage',
    category: 'Frontend',
    summary: 'Documentation on our internal Tailwind-based design system and reusable Atomic components.',
    views: 715,
    readTime: '8 min read',
    updatedAt: '3d ago',
    authorName: 'Sophia Lee',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=260&auto=format&fit=crop',
    imageUrl: 'https://blog.logrocket.com/wp-content/uploads/2023/06/Preline-UI.png',
  },
  {
    id: 'DOC-005',
    title: 'Node.js Error Handling Middleware',
    category: 'Documentation',
    summary: 'Standard patterns for global error middleware in Express apps for consistent REST responses.',
    views: 450,
    readTime: '6 min read',
    updatedAt: 'Updated 2h ago',
    authorName: 'Marcus Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=260&auto=format&fit=crop',
    imageUrl: 'https://cdn.educba.com/academy/wp-content/uploads/2020/03/Node.js-Error-Handling-768x427.jpg',
  },
  {
    id: 'DOC-006',
    title: 'Q3 Quarterly Review Prep Outline',
    category: 'Playbook',
    summary: 'Data visualization standards for client-facing performance reports and metrics highlights.',
    views: 520,
    readTime: '15 min read',
    updatedAt: 'Updated 1d ago',
    authorName: 'Elena Rodriquez',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=260&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=480&auto=format&fit=crop',
  },
  {
    id: 'DOC-007',
    title: 'Naming Conventions v2.1 Standards',
    category: 'Standards',
    summary: 'Revised variable and class naming standards for better maintainability and static lint rules.',
    views: 310,
    readTime: '10 min read',
    updatedAt: 'Updated 3d ago',
    authorName: 'John Doe',
    authorAvatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=260&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=480&auto=format&fit=crop',
  }
];
